import 'dart:io';

import 'package:flutter_inappwebview/flutter_inappwebview.dart';

import 'settings_storage.dart';

/// YouTube 登录 Cookie 存储
///
/// 登录弹窗里抓到的 cookie 写成 Netscape 格式 cookies.txt，
/// yt-dlp 下载 YouTube 时用 `--cookies` 加载，伪装成已登录浏览器，绕过机器人验证。
class YoutubeCookies {
  YoutubeCookies._();

  static const String fileName = 'youtube_cookies.txt';

  /// cookie 文件路径（应用支持目录下）
  static Future<File> cookieFile() async {
    final dir = await SettingsStorage.getStorageDir();
    return File('${dir.path}/$fileName');
  }

  /// 是否已有登录 cookie
  static Future<bool> hasCookies() async {
    try {
      final f = await cookieFile();
      return await f.exists() && await f.length() > 0;
    } catch (_) {
      return false;
    }
  }

  /// 把 webview 抓到的 cookie 写成 Netscape 格式
  static Future<void> saveCookies(List<Cookie> cookies) async {
    final buf = StringBuffer();
    buf.writeln('# Netscape HTTP Cookie File');
    buf.writeln('# This file is generated by Sownie. Do not edit.');
    buf.writeln();
    for (final c in cookies) {
      final domain = (c.domain?.isNotEmpty ?? false) ? c.domain! : '.youtube.com';
      final path = (c.path?.isNotEmpty ?? false) ? c.path! : '/';
      final secure = (c.isSecure ?? false) ? 'TRUE' : 'FALSE';
      final expiryMs = c.expiresDate ?? 0;
      final expiry = expiryMs > 0 ? expiryMs ~/ 1000 : 0;
      buf.writeln('$domain\tTRUE\t$path\t$secure\t$expiry\t${c.name}\t${c.value}');
    }
    final f = await cookieFile();
    await f.writeAsString(buf.toString());
  }

  /// 删除 cookie 文件（退出登录）
  static Future<void> clearCookies() async {
    try {
      final f = await cookieFile();
      if (await f.exists()) await f.delete();
    } catch (_) {}
  }
}
