import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

import 'settings_storage.dart';

/// 站点登录 Cookie 存储（按站点 id 分文件）
///
/// 登录弹窗抓到的 cookie 写成 Netscape 格式 cookies/{siteId}.txt，
/// yt-dlp 下载时把所有文件 `--cookies` 传进去，按域名自动匹配对应站的 cookie。
class SiteCookies {
  SiteCookies._();

  static Future<Directory> _cookieDir() async {
    final dir = await SettingsStorage.getStorageDir();
    final cdir = Directory('${dir.path}/cookies');
    if (!await cdir.exists()) await cdir.create(recursive: true);
    return cdir;
  }

  static Future<File> cookieFile(String siteId) async {
    final dir = await _cookieDir();
    return File('${dir.path}/$siteId.txt');
  }

  static Future<bool> hasCookies(String siteId) async {
    try {
      final f = await cookieFile(siteId);
      return await f.exists() && await f.length() > 0;
    } catch (_) {
      return false;
    }
  }

  /// 把 webview 抓到的 cookie 写成 Netscape 格式
  static Future<void> saveCookies(String siteId, List<Cookie> cookies) async {
    final buf = StringBuffer();
    buf.writeln('# Netscape HTTP Cookie File');
    buf.writeln('# This file is generated by 4KDownle. Do not edit.');
    buf.writeln();
    for (final c in cookies) {
      final domain = c.domain;
      if (domain == null || domain.isEmpty) continue;
      final path = (c.path?.isNotEmpty ?? false) ? c.path! : '/';
      final secure = (c.isSecure ?? false) ? 'TRUE' : 'FALSE';
      // includeSubdomains 必须和域名是否以 . 开头一致（.douyin.com→TRUE，www.douyin.com→FALSE），
      // 否则 Python http.cookiejar 会 assert domain_specified == initial_dot 报错
      final includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      final expiryMs = c.expiresDate ?? 0;
      final expiry = expiryMs > 0 ? expiryMs ~/ 1000 : 0;
      buf.writeln(
          '$domain\t$includeSubdomains\t$path\t$secure\t$expiry\t${c.name}\t${c.value}');
    }
    final f = await cookieFile(siteId);
    await f.writeAsString(buf.toString());
    debugPrint('[Cookie] 保存 ${cookies.length} 条到 ${f.path}');
  }

  static Future<void> clearCookies(String siteId) async {
    try {
      final f = await cookieFile(siteId);
      if (await f.exists()) await f.delete();
    } catch (_) {}
  }

  /// 所有已登录站点的 cookie 文件路径（下载时全部 --cookies 传给 yt-dlp）
  static Future<List<String>> allCookieFilePaths() async {
    try {
      final dir = await _cookieDir();
      final files = await dir.list().toList();
      return files
          .whereType<File>()
          .where((f) => f.path.endsWith('.txt'))
          .map((f) => f.path)
          .toList();
    } catch (_) {
      return const [];
    }
  }
}
